### ISSUE TITLE
Cannot read file error when testing notification to email with render

### ISSUE THREAD

**Issue by bonehead-animations** [SpectralVectors/RenderReminder#1]
![email_render_error](https://github.com/SpectralVectors/RenderReminder/assets/150308679/3d68f38e-2561-4f24-bdde-8559da6c125e)

_**Behavior**_
Had this error come up after clicking "Test Your Notification Settings" for the "Ding".  Showed the checkboxes above the Ding to show that it looks to be happening only when I check the box for "Attach Render to Email?"

_**Expectation**_
I would've expected this to send an email, and not to attempt to make an email attachment when testing.

_**Side Things**_ 
Thanks for having this project btw.  Was literally just thinking of making something like this and stumbled upon this.

Might go ahead and make a PR to fix this later, but tired at the moment and decided to just make an issue instead lol.

**Comment by SpectralVectors** [comment]
'Test your Notification Settings' will take into account **all** of the settings in the addon:
- Send Email (if checked)
- Attach Render (if checked)
- Play Sound (if checked)

I created the button so that I could send test emails quickly, if you uncheck 'Send Email' and 'Attach Render' and then click 'Test your Notification Settings' it will work as you were expecting.
